### ISSUE TITLE
Malformed Identity API 2.0 XML Request example for Multi-Factor Authentication Setup

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-identity#49]
_From @wdschei on August 12, 2016 21:27_
### Report an issue with the documentation

Describe your documentation issue in  the relevant section. Submit product operation or 
performance issues to the Rackspace product team at https://feedback.rackspace.com/.

**Link to documentation with issue:**  
https://developer.rackspace.com/docs/cloud-identity/v2/developer-guide/#generate-an-authentication-token

**Report incorrect information:**
This following example on the page linked above is malformed:

```
<?xml version="1.0" encoding="UTF-8"?>
<auth xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://docs.openstack.org/identity/api/v2.0">
  <RAX-AUTH:scope="SETUP-MFA"/>
  <passwordCredentials username="demoAuthor" password="myPassword01"/>
</auth>
```

Should it be:

```
<RAX-AUTH:scope>SETUP-MFA</RAX-AUTH:scope>
```

OR

```
<RAX-AUTH:scope UNKNOWN="SETUP-MFA"/>
```

Also the _XML_ examples are labeled as _JSON_

**Report editorial or format problem:** 
The title `Example: Authenticate as user with password or API key` followed shortly by `request` and `JSON` in alternating orders is used for all combinations of examples for _Password_ & _API Key_ and _JSON_ & _XML_. They should actually differentiate the example so the reader knows which ones are which.
- `Example: Authenticate as user with password request XML`
- `Example: Authenticate as user with password request JSON`
- `Example: Authenticate as user with API key request XML`
- `Example: Authenticate as user with API key request JSON`

**Report missing information:**

**Documentation feedback:**
I like the layout of the docs and I can usually discern what I need, but the attention to details (e.g. XML examples labeled as JSON) seem to be lacking.

_Copied from original issue: rackerlabs/docs-rackspace#176_

**Comment by wdschei** [comment]
All of the *editorial* and *format* issues are fixed in PR https://github.com/rackerlabs/docs-cloud-identity/pull/50.

The only outstanding issue is with the content of the example now uniquely identified as:

- `Example: Authenticate as user with Password for Multi-Factor Authentication Setup XML request`

**Comment by meker12** [comment]
Fixed the XML example. See https://developer.rackspace.com/docs/cloud-identity/v2/api-reference/token-operations/#authenticate-as-user-with-password-or-api-key. 

````
<?xml version="1.0" encoding="UTF-8"?>
   <auth xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://docs.openstack.org/identity/api/v2.0">
        <RAX-AUTH:scope="SETUP-MFA"/>
        <passwordCredentials username="demoAuthor" password="myPassword01"/>
  </auth>

````

**Comment by wdschei** [comment]
@meker12 The XML above and live at the link for the `Example: Authenticate as user with password for multi-factor authentication setup XML request` are still not well formed XML.

`<RAX-AUTH:scope="SETUP-MFA"/>`

Should be either:

`<RAX-AUTH:scope>SETUP-MFA</RAX-AUTH:scope>`

OR

`<RAX-AUTH:scope UNKNOWN="SETUP-MFA"/>`

That was the original issue that I was trying to get fixed. The secondary issue was that I couldn't reference it because all of the examples had the same title. The titles are now fixed, but the primary issue of the malformed XML has not been fixed.

**Comment by meker12** [comment]
@wdschei The example in the [Service Contracts repository](https://github.rackspace.com/ServiceAPIContracts/global-auth-keystone-extensions/blob/master/src/formattedsamples/AuthWithScope.xml) that is the Identity API contract source of truth shows this:

````
<?xml version="1.0" encoding="UTF-8"?>
<auth RAX-AUTH:scope="SETUP-MFA"
     xmlns="http://docs.openstack.org/identity/api/v2.0"
     xmlns:OS-KSADM="http://docs.openstack.org/identity/api/ext/OS-KSADM/v1.0"
     xmlns:RAX-AUTH="http://docs.rackspace.com/identity/api/ext/RAX-AUTH/v1.0" xmlns:atom="http://www.w3.org/2005/Atom">
     <passwordCredentials password="theUsersPassword" username="demoauthor"/>
</auth>
````
Looking at the domain mfa enforcement operation as an example:

````
<?xml version="1.0" encoding="UTF-8"?>
<domain domainMultiFactorEnforcementLevel="REQUIRED"
     enabled="true" id="9883948" name="GCorp" 
     xmlns="http://docs.rackspace.com/identity/api/ext/RAX-AUTH/v1.0"
     xmlns:OS-KSADM="http://docs.openstack.org/identity/api/ext/OS-KSADM/v1.0"
     xmlns:atom="http://www.w3.org/2005/Atom" xmlns:identity="http://docs.openstack.org/identity/api/v2.0">
     <description>A very good customer</description>
</domain>
````

I think the XML for MFA-SETUP should be: 

````
   <?xml version="1.0" encoding="UTF-8"?>
   <auth scope="SETUP-MFA" passwordCredentials password="myPassword01"
        username="demoauthor"
        xmlns="http://docs.openstack.org/identity/api/v2.0"
        xmlns:OS-KSADM="http://docs.openstack.org/identity/api/ext/OS-KSADM/v1.0"
        xmlns:RAX-AUTH="http://docs.rackspace.com/identity/api/ext/RAX-AUTH/v1.0"
        xmlns:atom="http://www.w3.org/2005/Atom">
   </auth>
````

Let me know if that works, and then we can correct the documentation. If it doesn't work, @RackerWilliams can probably help us get the correct syntax.

**Comment by wdschei** [comment]
Based on these new external examples, it looks like this example should probably be:
```
<?xml version="1.0" encoding="UTF-8"?>
<auth xmlns="http://docs.openstack.org/identity/api/v2.0"
      xmlns:RAX-AUTH="http://docs.rackspace.com/identity/api/ext/RAX-AUTH/v1.0"
      RAX-AUTH:scope="SETUP-MFA">
    <passwordCredentials username="demoAuthor" password="myPassword01"/>
</auth>
```
However I will definitely defer to @RackerWilliams or @rackerbob for verification.

**Comment by meker12** [comment]
So I was thinking that as long as the namespaces are declared, that you wouldn't have to use the RAX-AUTH with the scope, so will be interested to know the correct answer.  

Were you able to get your version to work @wdschei?

**Comment by wdschei** [comment]
I writing code in Repose to parse and use these responses. The version I posted earlier at least validates now. I will hold off final code modifications until we get a verified example.
